# CircleCI configuration file
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1
jobs:
  lint-frontend:
    docker:
      - image: cimg/node:21.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-dependencies-{{ checksum "frontend/package.json" }}
      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm install
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-dependencies-{{ checksum "frontend/package.json" }}
      - run: 
          name: Lint Frontend
          command: |
            cd frontend
            npm run lint
  lint-backend:
    docker:
      - image: cimg/node:21.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-dependencies-{{ checksum "backend/package.json" }}
      - run:
          name: Install Frontend Dependencies
          command: |
            cd backend
            npm install
      - save_cache:
          paths:
            - backend/node_modules
          key: backend-dependencies-{{ checksum "backend/package.json" }}
      - run: 
          name: Lint Backend
          command: |
            cd backend
            npm run lint
  build-and-push-images:
    executor: aws-ecr/default-executor
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          dockerfile: frontend/Dockerfile
          path: frontend/
          repo: frontend
          tag: 1.0
      - aws-ecr/build-and-push-image:
          dockerfile: backend/Dockerfile
          path: backend/
          repo: backend
          tag: 1.0

workflows:
  default:
    jobs:
      - lint-frontend
      - lint-backend
      - build-and-push-images